// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA39i4bFt8HRQiElQwyFyS8UtQZaD92n0w',
    appId: '1:1022825787582:web:649fe1f4fec131287eaeef',
    messagingSenderId: '1022825787582',
    projectId: 'hrodna-control',
    authDomain: 'hrodna-control.firebaseapp.com',
    storageBucket: 'hrodna-control.appspot.com',
    measurementId: 'G-N7Y70WHTGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB27_J6tF0I_7zNoRo4WTkazTot2SQ4lIY',
    appId: '1:1022825787582:android:5cda8d40233cd5d87eaeef',
    messagingSenderId: '1022825787582',
    projectId: 'hrodna-control',
    storageBucket: 'hrodna-control.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqdWawnroNzP7RFb3Q74Z7t-Quj4R5xNk',
    appId: '1:1022825787582:ios:43d9fa55c4d4d3e17eaeef',
    messagingSenderId: '1022825787582',
    projectId: 'hrodna-control',
    storageBucket: 'hrodna-control.appspot.com',
    iosClientId: '1022825787582-cleai4je6hgvmb0obtkf482gntbtvqc1.apps.googleusercontent.com',
    iosBundleId: 'by.gregory.hrodna-control',
  );
}
